apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
        - image: krawa/as-web
          name: web
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    run: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
  selector:
    run: web
